swipe:
  3:
    left:
      shortcut: 'super+w'
    right:
      shortcut: 'super+e'
    up:
      shortcut: 'super+m'
    down:
      shortcut: 'super+m'
  4:
    left:
      shortcut: 'super+Left'
    right:
      shortcut: 'super+Right'
    up:
      shortcut: 'super+m'
    down:
      shortcut: 'super+m'
pinch:
  in:
    shortcut: 'super+m'
  out:
     shortcut: 'super+m'

